SELECT
    C.NAME AS COUNTRY_NAME
  , C.POPULATION
  , C.REGION_ID
  , CR.NAME AS REGION_NAME
FROM
    EBA_COUNTRIES C
LEFT JOIN
    EBA_COUNTRY_REGIONS CR
ON
    C.REGION_ID = CR.ID;


SELECT
    C.NAME      AS COUNTRY_NAME
  , C.POPULATION
  , C.REGION_ID
  , CR.NAME     AS REGION_NAME
  , CSR.NAME    AS SUB_REGION_NAME
FROM
    EBA_COUNTRIES C
LEFT JOIN
    EBA_COUNTRY_REGIONS CR
ON
    C.REGION_ID = CR.ID
INNER JOIN
    EBA_COUNTRY_SUB_REGIONS CSR
ON
    C.SUB_REGION_ID = CSR.ID;
