CREATE TABLE EBA_COUNTRIES
(COUNTRY_ID NUMBER(4,0) NOT NULL, 
NAME VARCHAR2(100) NOT NULL, 
NATIONALITY VARCHAR2(100), 
COUNTRY_CODE VARCHAR2(3), 
ISO_ALPHA2 VARCHAR2(2), 
CAPITAL VARCHAR2(100), 
POPULATION NUMBER, 
AREA_KM2 NUMBER, 
REGION_ID NUMBER, 
SUB_REGION_ID NUMBER, 
INTERMEDIATE_REGION_ID NUMBER, 
ORGANIZATION_REGION_ID NUMBER);


CREATE TABLE EBA_COUNTRY_INTERMEDIATE
(ID NUMBER(4,0) NOT NULL, 
NAME VARCHAR2(255) NOT NULL);


CREATE TABLE EBA_COUNTRY_ORGANIZATIONS 
(ID NUMBER(4,0) NOT NULL , 
CODE VARCHAR2(100) NOT NULL , 
NAME VARCHAR2(255));



CREATE TABLE EBA_COUNTRY_REGIONS
(ID NUMBER(4,0) NOT NULL , 
NAME VARCHAR2(255) NOT NULL );


CREATE TABLE EBA_COUNTRY_SUB_REGIONS(
ID NUMBER(4,0) NOT NULL , 
NAME VARCHAR2(255) NOT NULL);

